### ISSUE TITLE
what is the password of login user raxda

### ISSUE THREAD

**Issue by wannacu** [radxa-build/rock-5b#1]
I used rock-5b_debian_bullseye_kde_2023-03-01T0719+0000_gpt.img.xz, and try login use rock/rock failed too.

**Comment by ticteam** [comment]
Hi, 
it would be very helyfull if you @wannacu share your soultion to others. 
I'm searching for the same. username and password for the image. 
already tried rock/rock radxa/radxa and root/root .... 
nothing works, I'm pretty sure there is a notice somewhere, but I'm not able to find it. 
thx

**Comment by RadxaYuntian** [comment]
It is radxa/radxa. Please post the system image link that you are using.

**Comment by ticteam** [comment]
I was testing rock-5b_debian_bullseye_xfce_b39.img.xz

**Comment by RadxaYuntian** [comment]
Please capture the boot log [with a serial cable](https://docs.radxa.com/en/rock5/rock5b/low-level-dev/serial), and send it to support@radxa.com for further assistance.
