### ISSUE TITLE
No HDMI Using Latest Rock 5B B39 nor After apt upgrade

### ISSUE THREAD

**Issue by keypunch416** [radxa-build/rock-5b#11]
Just received Rock 5B order few days ago.

First Rock 5B tested is Blue V1.46 8GB.

Image used was [latest Debian Bullseye CLI image b39](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_debian_bullseye_cli_b39.img.xz)

No HDMI on HDMI 1 nor HDMI 2.  Only using single monitor.  I am not trying to use two monitors.

Research suggested try to update image.  ssh works.  Via ssh performed `apt update` and `apt upgrade` that both completed successfully except u-boot related issues that will have separate issues opened.  Rebooted via ssh.  Still no HDMI on HDMI 1 or HDMI 2.

Kernel with b39 image was `Linux rock-5b 5.10.110-15-rockchip #a2d3d7e5d SMP Mon Sep 4 11:55:03 UTC 2023 aarch64 GNU/Linux`.
Kernel post `apt upgrade` was `Linux rock-5b 5.10.110-29-rockchip #395062847 SMP Mon Jan 22 08:42:41 UTC 2024 aarch64`.

Tried rsetup a few times related to HDMI, but changes believe made related to HDMI had no effect even after reboot of each rsetup attempt.

**Comment by RadxaYuntian** [comment]
CLI variant is for headless usage. If you want graphic you should use the desktop variant.

**Comment by keypunch416** [comment]
All CLI versions of any other CLI image image I have used for over 30 years the display has always worked with VGA, Display Port, or HDMI as well as keyboard via Serial, PS/2 or USB.  Debian CLI out of box CLI works with display and keyboard for any system be is ARM based or otherwise.   This means VGA, Display Port, and HDMI working for console is very basic requirement to use of any Unix and does not require any desktop to be installed.  Headless means using SSH most of time, but does not mean that the display and keyboard does not work because the image is CLI only.  There are also use cases for CLI  for local use and now network is even available, hence no headless via ssh is not even possible on purpose or due to very remote or security isolated requirement of the system.  This means display and keyboard need to work with a CLI only image where the environment has no network access at all.  A very important reason for display and keyboard working for CLI is when using via ssh is if any problem occurs during boot that needs console access via display and keyboard to work so one can connect display and keyboard in order to see the reasons the boot will not complete or is taking long time due to some timeout issue that needs to be fixed.  In fact there is a unusually long delay in the boot of the Rock 5B CLI image I cannot see and resolve because the display and maybe keyboard for CLI only image does not work.  That includes instances where the normally used headless system then requires visit to the remote site to use display and keyboard to see and resolve the issue so system can work again via ssh remotely.  Display and keyboard functioning is needed for such instances needs to work and again for over 30 years and for all other SBC images works.  I know as sometimes an update or some change or typing mistake I made means system will not boot where I connect display and USB keyboard to observe the issue and fix the issue.  With the Rock 5B image I cannot see nor resolve such issues I have been able to do so for over 30 years and with any other SBC image from any other vendor.

**Comment by RadxaYuntian** [comment]
> All CLI versions of any other CLI image image I have used for over 30 years the display has always worked with VGA

Rockchip SDK contains a bunch of hacks to enable its graphical stack. On our CLI image we do not install any Rockchip packages since their interdependence is a mess (result of them not considering CLI usage in the first place), and as a result we cannot guarantee display works in CLI images.

Installing said packages considerably increased the image size, and at that point you should just use the desktop variant.

**Comment by keypunch416** [comment]
No. I do not want to use desktop variant.  I only use CLI as all I need. Desktop variant used more power than CLI no matter if SBC or "standard" PC.  As you pointed out Desktop variant is much larger image than CLI.  I find it difficult to believe that what is needed to have HDMI work takes that much extra space.  HDMI works with Armbian CLI Rock 3A just fine and the image size if as expect for CLI and not near size of Desktop image.

**Comment by RadxaYuntian** [comment]
The issue is that Rockchip SDK does not properly define their package dependencies, since they expect you to install everything. As such we also [install everything](https://github.com/radxa-pkg/vendor-profiles/blob/main/debian/control#L222-L226) if we do want to install Rockchip packages.

Rockchip packages also requires [specific configurations](https://github.com/radxa-pkg/radxa-system-config/blob/main/debian/control#L19), which would be in conflict with other SoC. So in CLI images those are not installed as well.

You are more than welcome to try it yourself, but we currently cannot support custom images that cherry-pick features from Rockchip SDK, because the SDK itself does not support this usage.

**Comment by keypunch416** [comment]
With all due respect the DietPi V9.1 minimal CLI [image](https://dietpi.com/downloads/images/DietPi_ROCK5B-ARMv8-Bookworm.img.xz) works with HDMI for console connected to HDMI 1 on Rock 5B board.  If DietPI can do so why is it Radxa cannot?  Also, Rock Pi 4B+ image also works with HDMI CLI image.

**Comment by keypunch416** [comment]
With all due respect the Armbian minimal CLI [https://dl.armbian.com/rock-5b/archive/Armbian_23.2.1_Rock-5b_bookworm_legacy_5.10.160_minimal.img.xz](https://dl.armbian.com/rock-5b/archive/Armbian_23.2.1_Rock-5b_bookworm_legacy_5.10.160_minimal.img.xz) works with HDMI for console connected to HDMI 1 on Rock 5B board. If DietPI and Armbian can do so why is it Radxa cannot?
