### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by kalyanikasam** [radxa-build/rock-5b#17]
I have tried Debian11 and Ubuntu KDE b39 official radxa images. 
1.I am not able to use mali gpu instead llvmpipe is used by default. Can you suggest a way to enable hardware acceleration.
2.When radxa touch screen is connected and overlay enabled. By default x11 windowing system is used, i am not able to change the windowing system to wayland during login.

**Comment by RadxaYuntian** [comment]
> 1.I am not able to use mali gpu instead llvmpipe is used by default. Can you suggest a way to enable hardware acceleration.

You are most likely using OpenGL, which is unsupported by Mali. You should use OpenGL ES related tools to have GPU working.

> 2.When radxa touch screen is connected and overlay enabled. By default x11 windowing system is used, i am not able to change the windowing system to wayland during login.

We do not support Wayland on Debian 11 for Rockchip SDK based devices (basically everything not using RK3308 or RK3328). The test on current Debian 12 Rockchip SDK showed that Wayland is still broken with their SDK, so it won't be supported on that release either.

**Comment by kalyanikasam** [comment]
Even though i am not using any tools. In device about information Graphics is shown as llvmpipe instead of mali after fresh installation. Does it mean i need to install required drivers if yes what is the procedure please advice.
![Ubuntu KDE about info](https://github.com/radxa-build/rock-5b/assets/152457453/743e3c62-7a9f-4a37-906f-7c5b700a0878)

**Comment by RadxaYuntian** [comment]
I just realize that you are using Ubuntu. In which case there is no Mali driver installed, as that is a Rockchip provided package. Rockchip only supports Debian with their SDK, which means their packages may not be installable on Ubuntu due to different package version provided (thus breaking package dependencies). This is the reason we do not install them on Ubuntu, and we will stop providing Ubuntu image in the future.

However, even with our Debian system, that line should still be `llvmpipe`, as it is reporting only the OpenGL renderer.

**Comment by kalyanikasam** [comment]
I have even tried Debian11 b39 official  radxa image, as you said the system still shows llvmpipe. My requirement is to obtain video recording. In Debian system i have used OBS to do video recording and the CPU usage went upto 80% obviously it is using llvmpipe. I realized that OBS is using OpenGL and not OpenGL ES  as per your explanation above . After your clarification i realize that i cannot enable mali in Ubuntu. I am left with Debian option only. 
Could you suggest me a way to perform video recording on Debian making use of mali.

**Comment by RadxaYuntian** [comment]
Rockchip has its "proprietary" video acceleration API called MPP, which is not supported by OBS (using upstream FFmpeg). They provide [documentations](https://gitlab.com/rockchip_linux_sdk_6.1/linux/bsp/docs/-/blob/en/Linux/Multimedia/Rockchip_User_Guide_Linux_Gstreamer_EN.pdf?ref_type=heads) for how to use it, but those are targeting developers.

For now there is no good way to enable it on our system. You can try image from [here](https://joshua-riek.github.io/ubuntu-rockchip-download/) which might contains the patched FFmpeg. Though whether OBS can use it is another question.

**Comment by kalyanikasam** [comment]
Thank you for your suggestion. I have tried JoshuaRiek Ubuntu22.04 LTS image https://github.com/Joshua-Riek/ubuntu-rockchip
I suppose this is the same image you are suggesting. I could use OBS for video recording using h/w acceleration with this image.
The CPU usage was also about 40%. Issue is when i am connecting radxa touchscreen after enabling overlay in /boot/firmware/ubuntuEnv.txt in this image. The touch functionality is not there, it is working as normal display. And by default it is using x11 windowing system. I am facing issues installing OBS on x11.

**Comment by RadxaYuntian** [comment]
Yes that's the image I'm suggesting. You will have to contact that project if you encounter issues with their systems.
