### ISSUE TITLE
4k 120 hz

### ISSUE THREAD

**Issue by woiza** [radxa-build/rock-5b#20]
Hi,

I noticed Rock 5B can output 4k120 (4:2:0) via HDMI using your latest image. How did you achieve this? I tried several community images (Armbian, Joshua Riek, etc.). All of them can only output 4k 60 hz via HDMI.
Where can I see how you built the kernel and what changes were necessary for 4k120?

**Comment by RadxaYuntian** [comment]
Source code is available [here](https://github.com/radxa/kernel/tree/linux-6.1-stan-rkr1). The build tool can be found [here](https://radxa-repo.github.io/bsp/), which would make some additional adjustment to the code. This is to ensure a common experience across our various supported kernel forks.
