### ISSUE TITLE
Rock5b network problems with the wireless a8 module

### ISSUE THREAD

**Issue by schnellert** [radxa-build/rock-5b#23]
Hello everyone,

I am using the latest Debian version from the Github releases (https://github.com/radxa-build/rock-5b/releases -> 5b_bookworm_kde) with the Wireless a8 module (v2.0 -> AW-XB547NF) from you for the Rock5b.

My problem now is that only one WLAN appears under `nmcli d` instead of two. On a 22.04 Ubuntu system I have 'wlan0' and 'wlan1' here.

Can you help me?

**Comment by RadxaYuntian** [comment]
Which 22.04 Ubuntu system you are talking about?

**Comment by schnellert** [comment]
On your latest Ubuntu CLI release. This is the 22.04 version and an official radxa release.

I think that:
[rock-5b_ubuntu_jammy_cli_b39.img.xz](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_ubuntu_jammy_cli_b39.img.xz)

**Comment by schnellert** [comment]
On the version:
Ubuntu 22.04 - [LINK](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_ubuntu_jammy_cli_b39.img.xz)
Does wlan0 and wlan1 work with the Wireless a8 module.

On the version:
Debian 12 - https://github.com/radxa-build/rock-5b/releases/download/rsdk-b5/rock-5b_bookworm_kde_b5.output.img.xz
Does wlan0 and wlan1 NOT work with the Wireless a8 module. I only have one wlan and one ethernet interface there.

**Comment by schnellert** [comment]
it probably has errors when loading the driver. But that should actually be plug and play, right?
![image](https://github.com/user-attachments/assets/4e2e6162-0908-4c86-a4d7-2594635d29a2)

**Comment by RadxaYuntian** [comment]
The 2nd line told you it found the default firmware.

**Comment by CodeChenL** [comment]
@schnellert After testing, this is most likely due to driver differences, you can try to use this driver: https://github.com/lwfinger/rtw8852be. 
You need to remove the rtw89 driver before loading the 8852be.ko: 
```
sudo modprobe -r rtw_8852be
sudo modprobe -r rtw89core
```

**Comment by schnellert** [comment]
@CodeChenL, I have tried it.

My steps:
```
sudo modprobe -r rtw_8852be
sudo modprobe -r rtw89core

sudo apt-get update
sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git

git clone https://github.com/lwfinger/rtw8852be.git
cd rtw8852be
make
```

, but with 'make' i get this:
![image](https://github.com/user-attachments/assets/70017423-9884-4a10-8064-d00094b31562)

**Comment by CodeChenL** [comment]
> @CodeChenL, I have tried it.
> 
> My steps:
> 
> ```
> sudo modprobe -r rtw_8852be
> sudo modprobe -r rtw89core
> 
> sudo apt-get update
> sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git
> 
> git clone https://github.com/lwfinger/rtw8852be.git
> cd rtw8852be
> make
> ```
> 
> , but with 'make' i get this: ![image](https://private-user-images.githubusercontent.com/61295382/388089009-70017423-9884-4a10-8064-d00094b31562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTU4MzYsIm5iZiI6MTczMjE1NTUzNiwicGF0aCI6Ii82MTI5NTM4Mi8zODgwODkwMDktNzAwMTc0MjMtOTg4NC00YTEwLTgwNjQtZDAwMDk0YjMxNTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyMTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNDUyYzMyOTJhODgyOTcxZDY4YmViM2ZhOWM2OTUxNzg1MWY2YjI1NDRlZDBhY2RjODZhOWQ5YmQxNWMwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eCTt8UA_nB7VuBIWO6SPz5fkRo_oH_nhtZpo-Gn2mYQ)

Oh, sorry forgot to describe my changes to you.
```diff
diff --git a/Makefile b/Makefile
index c2bfc74..a574942 100644
--- a/Makefile
+++ b/Makefile
@@ -14,6 +14,7 @@ EXTRA_CFLAGS += -Wno-unused-label
 #EXTRA_CFLAGS += -Wno-unused-function
 EXTRA_CFLAGS += -Wno-unused
 #EXTRA_CFLAGS += -Wno-uninitialized
+EXTRA_CFLAGS += -Wno-error=address
 
 GCC_VER_49 := $(shell echo `$(CC) -dumpversion | cut -f1-2 -d.` \>= 4.9 | bc )
 ifeq ($(GCC_VER_49),1)
@@ -41,7 +42,7 @@ CONFIG_SDIO_HCI = n
 CONFIG_GSPI_HCI = n
 ########################## Features ###########################
 CONFIG_MP_INCLUDED = n
-CONFIG_CONCURRENT_MODE = n
+CONFIG_CONCURRENT_MODE = y
 CONFIG_POWER_SAVING = n
 CONFIG_POWER_SAVE = y
 CONFIG_IPS_MODE = default
```

**Comment by schnellert** [comment]
Hi,
I was able to install the driver and it seems to work.

But now I'm missing with:
`sudo iw phy phy0 info`

"set_wiphy_netns" as supported command.

Could it be that the driver is breaking something here?

**Comment by schnellert** [comment]
This had worked before the installation.

**Comment by CodeChenL** [comment]
> @CodeChenL, I was able to install the driver and it seems to work. Thanks.我成功安装了驱动程序，看起来它运行正常。谢谢。
> 
> But now I'm missing with:但是我现在缺少以下内容： `sudo iw phy phy0 info`
> 
> "set_wiphy_netns" as supported command."set_wiphy_netns" 作为支持的命令。
> 
> Could it be that the driver is breaking something here?可能是驱动程序在这里破坏了某些东西？

Hi @schnellert, 
Repeated unloading and loading of drivers in a single boot will change the phy index, try using the command `sudo rfkill` to see the phy*.

**Comment by schnellert** [comment]
@CodeChenL, okay. Is there still a way to fix this?
`sudo rfkill`
=
![image](https://github.com/user-attachments/assets/c26eb684-8f4c-48d1-ab69-43dde20388da)

&
`sudo rfkill list all`
=
![image](https://github.com/user-attachments/assets/b8f41afc-1abe-408b-957b-646358910f8a)

**Comment by schnellert** [comment]
I need two wlan interfaces + 'set_wiphy_netns' as supported command. That must be possible somehow :D

**Comment by schnellert** [comment]
`set_wiphy_netns` appears again if you modify the following in the driver:
https://github.com/schnellert/rtw8852be/pull/2

^Felix
