### ISSUE TITLE
Rock5b, Ubuntu 22.04 and wireless A8 module 

### ISSUE THREAD

**Issue by schnellert** [radxa-build/rock-5b#24]
Hello again,

Here is the context of an other issue:
https://github.com/radxa-build/rock-5b/issues/23

This was about getting the "RTW8852BE" driver for Debian 12 bookworm working.

This worked by setting `CONFIG_CONCURRENT_MODE = y` in the Makefile and adding `EXTRA_CFLAGS += -Wno-error=address`.

More details in the issue.

My question now:
How do I get this driver to run on the Rock5b for Ubuntu 22.04 jammy CLI?

I have done the following as described in the other issue (above changes already adopted):
```
sudo apt-get update -y
sudo sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git

git clone https://github.com/lwfinger/rtw8852be.git
cd rtw8852be
make
```

.. and with make it fails with the following error:
![image](https://github.com/user-attachments/assets/4fca9973-52c7-4684-871d-96cd30c11c03)

Do i need a customised Makefile configuration here again?

Best regards,
Felix

**Comment by schnellert** [comment]
And which driver would I have to fire in the event of a new build?

Because you won't find any under "rtw" here:
![image](https://github.com/user-attachments/assets/c955e025-4627-490a-8060-cc3a5bafe2f6)

**Comment by RadxaYuntian** [comment]
You should ask questions in that repository. We used to support own own [8852be](https://github.com/radxa-pkg/8852be-dkms) package but it is now replaced by upstream driver.

**Comment by schnellert** [comment]
kk, thanks.
