### ISSUE TITLE
With driver customisation 'set_wiphy_netns' should works

### ISSUE THREAD

**Issue by schnellert** [radxa-build/rock-5b#25]
Hello again,

A context about a problem:
https://github.com/radxa-build/rock-5b/issues/23

I have made a few adjustments to the RTW8852BE driver so that `set_wiphy_netns` should works.

I wanted to ask if there is any reason why you don't ship this by default?

My adjustments:
https://github.com/schnellert/rtw8852be/pull/2

Best regards,
Felix

**Comment by RadxaYuntian** [comment]
Because we don't use vendor driver anymore due to performance issue. We are using [upstream driver](https://github.com/radxa-pkg/radxa-profiles/commit/45edf7005642f39da4da6e3ef1d5adf4ab131b44).
