### ISSUE TITLE
Moonlight-qt Rock 5B

### ISSUE THREAD

**Issue by woiza** [radxa-build/rock-5b#26]
Hi,

I built [moonlight-qt](https://github.com/moonlight-stream/moonlight-qt) following the instructions  on their GitHub page. The app starts, however without hardware acceleration. Hardware acceleration works with Chrome (tested with Youtube).
Do you know how I can build/use moonlight with hardware acceleration using your latest image and kernel? Do you provide a moonlight-qt package/repo?

**Comment by RadxaYuntian** [comment]
You will need to build with FFmpeg that support Rockchip video acceleration, like [this one](https://github.com/jellyfin/jellyfin-ffmpeg).

The included Chromium is patched by Rockchip to support video acceleration. If you build from source it won't work as well.

It is quite difficult to replace the system's default FFmpeg implementation, which is why this hasn't been done yet, and we are unable to assist you to build Moonlight with Jellyfin's FFmpeg.

**Comment by woiza** [comment]
@RadxaYuntian I was able to build moonlight-qt with [ffmpeg-rockchip](https://github.com/nyanmisaka/ffmpeg-rockchip). Thank you for your help and the explanation!

**Comment by RadxaYuntian** [comment]
Mind share how you did it?

**Comment by woiza** [comment]
1. new installation of your image
2. update/upgrade using rsetup, then reboot
3. apt autopurge, then reboot
4. build mpp, rga, ffmpeg following this (I had to install `build-essential`too):
[ffmpeg compilation](https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Compilation)
and add `--enable-shared` when configuring ffmpeg
5. Follow the moonlight-qt readme:
[moonlight-qt](https://github.com/moonlight-stream/moonlight-qt)
and install all required packages for Debian/Ubuntu and Qt 6
6. Add the following line to `moonlight-qt.pro` and `app/app.pro`:
`LIBS += -L/usr/lib -lavcodec -lavutil -lavformat -lswscale`
7. Build moonlight: `make release`
8. Verify moonlight uses ffmpeg-rockchip libs: `ldd app/moonlight`

**Comment by woiza** [comment]
@RadxaYuntian according to [moonlight-docs](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-ARM%E2%80%90based-Single-Board-Computers) RK3588 currently lacks V4L2 drivers.
Do you know if Rockchip or someone else works on V4L2 drivers?

**Comment by RadxaYuntian** [comment]
Upstream [is working on this](https://lwn.net/Articles/930790/).

That page should be for their prebuilt packages only. You build with custom FFmpeg so you should not be affected.

**Comment by RadxaYuntian** [comment]
@CodeChenL check if you can create some documentation based on the above steps. I think we already have some to build custom FFmpeg but not the its down stream users.

**Comment by woiza** [comment]
@RadxaYuntian 
I can set HDMI to 4k120 4:2:0 on my Rock 5B with your image. My tv supports 4k120 4:4:4. Do you know how I can enable this?
How can I turn on HDR?
How were you able to achieve 4k120? I tried other images (Armbian, Joshu Riek, etc.), they all max out at 4k60. Could you please share some documentation/information on how to configure 4k120 with this kernel?

**Comment by CodeChenL** [comment]
> @RadxaYuntian I can set HDMI to 4k120 4:2:0 on my Rock 5B with your image. My tv supports 4k120 4:4:4. Do you know how I can enable this? How can I turn on HDR? How were you able to achieve 4k120? I tried other images (Armbian, Joshu Riek, etc.), they all max out at 4k60. Could you please share some documentation/information on how to configure 4k120 with this kernel?

You can open 4: 4: 4 in the settings of MoonLight, but this also requires the Sunshine host encoder support

**Comment by woiza** [comment]
@RadxaYuntian thanks, but I want to know how I can set your OS to 4k120 4:4:4. As soon as I enable 4k120 in the Debian display settings, my Rock 5B "outputs" 4k120 4:2:0.

**Comment by CodeChenL** [comment]
> @RadxaYuntian thanks, but I want to know how I can set your OS to 4k120 4:4:4. As soon as I enable 4k120 in the Debian display settings, my Rock 5B "outputs" 4k120 4:2:0.

The default setting is `rgb888`, which is equivalent to `yuv444`?You can use the command `xrandr --verbose` to view available parameters and current settings, and use `xrandr --output <display port> --set <option> <value>` to set them.
