### ISSUE TITLE
Config partition size to small to be auto assigned a drive letter in Windows

### ISSUE THREAD

**Issue by raphaelscholle** [radxa-build/rock-5b#4]
Can you increase the partition size of the config partition?
The issue is that such small partitions aren't assigned a drive letter automatically and users need to do that manually, each time they want to write to said partition.

**Comment by RadxaYuntian** [comment]
I assume you are using Windows when you talk about drive letter. Can you confirm that so I can send tester on this issue?

**Comment by raphaelscholle** [comment]
Yes I'm using windows (11), in my tests it always need's to be assigned the drive letter manually to write to it

**Comment by RadxaYuntian** [comment]
I tried on 2 Windows 11 machines and they can assign the drive letter to the config partition without issue. Can you check on some other machine, and provide me the image you are using?
